Repository nnstreamer/api, pull requests merged in 2021-05, with the labels that each got.

#50 [C-Api] enum for AIFW
  c/include/nnstreamer.h
  c/src/nnstreamer-capi-util.c
Labels: ACR required

#51 [Spec] Add the Provides option in case of 64bit
  packaging/machine-learning-api.spec
Labels: DO NOT MERGE

#29 [SRNPU/NNFW] Add NNFW Type for SRNPU
  c/include/nnstreamer.h
  c/src/nnstreamer-capi-single.c
  c/src/nnstreamer-capi-util.c
Labels: ACR required, DO NOT MERGE

#37 [API/Skeleton] App Src Callback support
  c/include/nnstreamer.h
  c/src/nnstreamer-capi-pipeline.c
Labels: ACR required
