Repository nnstreamer/api, pull requests merged in 2024-04, with the labels that each got.

#469 [C-Api/Service] update ml-service pipeline
  c/include/ml-api-service.h
  c/src/ml-api-remote-service.c
  c/src/ml-api-service-agent-client.c
  tests/capi/unittest_capi_remote_service.cc
  tests/capi/unittest_capi_service_agent_client.cc
Labels: DO NOT MERGE, ACR required

#492 [C-Api/Service] change ml-agent param
  c/src/ml-api-service-agent-client.c
Labels: PR/Ready2Go

#493 [CodeClean] remove unnecessary code
  c/src/ml-api-service-offloading.c
  c/src/ml-api-service-offloading.h
  c/src/ml-api-service-private.h
  tests/capi/unittest_capi_service_offloading.cc
Labels: PR/Ready2Go

#472 [C-Api/Service] update ml-service pipeline
  c/include/ml-api-service.h
  c/src/ml-api-service-agent-client.c
  tests/capi/unittest_capi_service_agent_client.cc
Labels: ACR required

#471 [C-Api/Service] update ml-service pipeline
  c/include/ml-api-service.h
  c/src/ml-api-service-agent-client.c
  tests/capi/unittest_capi_service_agent_client.cc
Labels: ACR required

#499 [Android] change tflite option in JNI and build scripts
  java/android/nnstreamer/build.gradle
  java/android/nnstreamer/src/main/jni/Android-tensorflow-lite.mk
  java/android/nnstreamer/src/main/jni/Android.mk
  java/build-nnstreamer-android.sh
Labels: PR/Ready2Go
