Repository nnstreamer/api, pull requests merged in 2024-09, with the labels that each got.

#558 [CodeClean] fix typo
  c/src/ml-api-internal.h
Labels: trivial

#550 enable tensor-rt with C-API
  c/include/ml-api-common.h
  c/src/ml-api-inference-single.c
Labels: ACR required

#555 [single] Add ML_NNFW_TYPE enum for QNN
  c/include/ml-api-common.h
  c/src/ml-api-inference-single.c
Labels: ACR required

#565 [Doc] Fix the typo in example code
  c/include/nnstreamer.h
Labels: Tizen 9.0 M2
